### ISSUE TITLE
Add UDP port for broader compatibility

### ISSUE THREAD

**Issue by djuniversal** [tenox7/vnc4bro#1]
UDP port also needs to be exposed in certain VNC setups. 

Add  -p 5900:5900/udp command to docker run command, or 
-port
  '5900:5900/udp'
to your docker compose file

**Comment by tenox7** [comment]
thanks for the suggestion, but I never heard VNC supporting UDP protocol, tightvnc and tigervnc do not support UDP IMHO

feel free to re-open as needed
